//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagacinskoRobnoMaterijalno.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentItem
    {
        public long ID { get; set; }
        public long DocumentID { get; set; }
        public decimal ItemPrice { get; set; }
        public string ArticleNo { get; set; }
        public long ItemID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityItemPrice { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public string Note { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Surface { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Document Document { get; set; }
    }
}
