// <auto-generated />
namespace MagacinskoRobnoMaterijalno.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Pocetak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pocetak));
        
        string IMigrationMetadata.Id
        {
            get { return "201911082038268_Pocetak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
