// <auto-generated />
namespace MagacinskoRobnoMaterijalno.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class izmena12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(izmena12));
        
        string IMigrationMetadata.Id
        {
            get { return "201911090105045_izmena12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
