// <auto-generated />
namespace MagacinskoRobnoMaterijalno.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class promena171 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promena171));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101641584_promena171"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
