// <auto-generated />
namespace MagacinskoRobnoMaterijalno.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class promena_7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promena_7));
        
        string IMigrationMetadata.Id
        {
            get { return "201911050010072_promena_7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
